### ISSUE TITLE
FragmentTransition error with the last version of Android Support

### ISSUE THREAD

**Issue by melkir** [googlesamples/android-OurStreets#2]
When I'm using the latest appcompat version I have the following error if I click on an item

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.google.samples.apps.ourstreets, PID: 27667
                  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                      at android.support.v4.app.FragmentTransitionCompat21.setNameOverridesOptimized(FragmentTransitionCompat21.java:339)
                      at android.support.v4.app.FragmentTransition.configureTransitionsOptimized(FragmentTransition.java:232)
                      at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:111)
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2143)
                      at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:709)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7229)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
```

Here is my build.gradle
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        applicationId "com.google.samples.apps.ourstreets"
        minSdkVersion 21
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        // This url is being defined in gradle.properties and can be changed from there.
        buildConfigField "String", "GALLERIES_URL", "\"${galleries_url}\""
        buildConfigField "String", "DETAIL_URL", "\"${detail_url}\""
    }
    buildTypes {
        debug {
            resValue "string", "google_maps_key", "\"${maps_api_key}\""
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE-FIREBASE.txt'
        exclude 'META-INF/NOTICE'
    }
}

ext {
    appCompatVersion = "25.1.0"
}

dependencies {
    compile "com.android.support:appcompat-v7:${appCompatVersion}"
    compile "com.android.support:cardview-v7:${appCompatVersion}"
    compile "com.android.support:design:${appCompatVersion}"
    compile "com.android.support:recyclerview-v7:${appCompatVersion}"
    compile "com.firebase:firebase-client-android:2.5.2"
    compile "com.google.android.gms:play-services-maps:10.0.1"
    compile "com.google.maps.android:android-maps-utils:0.4"
    testCompile 'junit:junit:4.12'
    testCompile "org.hamcrest:hamcrest-core:1.3"
    testCompile "org.hamcrest:hamcrest-library:1.3"
}
```

**Comment by keyboardsurfer** [comment]
Thanks for reporting this issue.
I don't see why the support library version needs to be bumped at this point in time.
Could you explain the rationale behind it?
